STEP 0: link-to-central-grasp (link3,link4,joint4,joint3,gleft,gright)
STEP 1: decrease-release (link4,link3,joint3,gleft,gright,angle60,angle0)
STEP 2: link-to-central-grasp (link4,link5,joint4,joint4,gleft,gright)
STEP 3: decrease-release (link5,link4,joint4,gleft,gright,angle60,angle0)
STEP 4: link-to-central-grasp (link3,link4,joint3,joint3,gleft,gright)
STEP 5: increase-release (link4,link3,joint3,gleft,gright,angle0,angle300)
