STEP 0: link-to-central-grasp (link4,link5,joint4,joint4,gleft,gright)
STEP 1: decrease-release (link4,link5,joint4,gleft,gright,angle180,angle120)
STEP 2: link-to-central-grasp (link3,link4,joint1,joint3,gleft,gright)
STEP 3: decrease-release (link4,link3,joint3,gleft,gright,angle120,angle60)
STEP 4: link-to-central-grasp (link3,link4,joint1,joint3,gleft,gright)
STEP 5: decrease-release (link4,link3,joint3,gleft,gright,angle60,angle0)
STEP 6: link-to-central-grasp (link4,link3,joint1,joint3,gleft,gright)
STEP 7: increase-release (link3,link4,joint3,gleft,gright,angle120,angle180)
