STEP 0: link-to-central-grasp (link5,link4,joint5,joint4,gleft,gright)
STEP 1: increase-release (link5,link4,joint4,gleft,gright,angle180,angle270)
STEP 2: link-to-central-grasp (link3,link2,joint1,joint2,gleft,gright)
STEP 3: increase-release (link2,link3,joint2,gleft,gright,angle0,angle90)
STEP 4: link-to-central-grasp (link3,link2,joint1,joint2,gleft,gright)
STEP 5: decrease-release (link3,link2,joint2,gleft,gright,angle180,angle90)
STEP 6: link-to-central-grasp (link5,link6,joint1,joint5,gleft,gright)
STEP 7: decrease-release (link5,link6,joint5,gleft,gright,angle180,angle90)
