STEP 0: link-to-central-grasp (link2,link3,joint2,joint2,gleft,gright)
STEP 1: decrease-release (link3,link2,joint2,gleft,gright,angle180,angle90)
STEP 2: link-to-central-grasp (link2,link1,joint1,joint1,gleft,gright)
STEP 3: increase-release (link1,link2,joint1,gleft,gright,angle0,angle270)
STEP 4: link-to-central-grasp (link4,link3,joint6,joint3,gleft,gright)
STEP 5: increase-release (link3,link4,joint3,gleft,gright,angle90,angle180)
STEP 6: link-to-central-grasp (link4,link3,joint6,joint3,gleft,gright)
STEP 7: decrease-release (link4,link3,joint3,gleft,gright,angle90,angle0)
