STEP 0: link-to-central-grasp (link2,link3,joint4,joint2,gleft,gright)
STEP 1: decrease-release (link3,link2,joint2,gleft,gright,angle90,angle0)
STEP 2: link-to-central-grasp (link4,link3,joint4,joint3,gleft,gright)
STEP 3: increase-release (link4,link3,joint3,gleft,gright,angle0,angle90)
STEP 4: link-to-central-grasp (link4,link5,joint1,joint4,gleft,gright)
STEP 5: increase-release (link5,link4,joint4,gleft,gright,angle0,angle90)
