STEP 0: link-to-central-grasp (link2,link3,joint2,joint2,gleft,gright)
STEP 1: increase-release (link2,link3,joint2,gleft,gright,angle0,angle90)
STEP 2: link-to-central-grasp (link3,link4,joint1,joint3,gleft,gright)
STEP 3: decrease-release (link3,link4,joint3,gleft,gright,angle270,angle180)
STEP 4: link-to-central-grasp (link2,link3,joint1,joint2,gleft,gright)
STEP 5: decrease-release (link3,link2,joint2,gleft,gright,angle180,angle90)
