STEP 0: link-to-central-grasp (link3,link4,joint1,joint3,gleft,gright)
STEP 1: increase-release (link4,link3,joint3,gleft,gright,angle0,angle90)
STEP 2: link-to-central-grasp (link2,link1,joint1,joint1,gleft,gright)
STEP 3: decrease-release (link2,link1,joint1,gleft,gright,angle270,angle180)
STEP 4: link-to-central-grasp (link1,link2,joint2,joint1,gleft,gright)
STEP 5: decrease-release (link2,link1,joint1,gleft,gright,angle180,angle90)
