STEP 0: link-to-central-grasp (link1,link2,joint2,joint1,gleft,gright)
STEP 1: increase-release (link1,link2,joint1,gleft,gright,angle0,angle270)
STEP 2: link-to-central-grasp (link4,link5,joint2,joint4,gleft,gright)
STEP 3: increase-release (link4,link5,joint4,gleft,gright,angle90,angle180)
STEP 4: link-to-central-grasp (link3,link4,joint2,joint3,gleft,gright)
STEP 5: increase-release (link4,link3,joint3,gleft,gright,angle180,angle270)
STEP 6: link-to-central-grasp (link3,link2,joint4,joint2,gleft,gright)
STEP 7: increase-release (link3,link2,joint2,gleft,gright,angle90,angle180)
