STEP 0: link-to-central-grasp (link2,link1,joint1,joint1,gleft,gright)
STEP 1: decrease-release (link2,link1,joint1,gleft,gright,angle90,angle0)
STEP 2: link-to-central-grasp (link3,link4,joint3,joint3,gleft,gright)
STEP 3: decrease-release (link4,link3,joint3,gleft,gright,angle180,angle90)
STEP 4: link-to-central-grasp (link5,link4,joint4,joint4,gleft,gright)
STEP 5: decrease-release (link5,link4,joint4,gleft,gright,angle270,angle180)
