STEP 0: link-to-central-grasp (link5,link4,joint4,joint4,gleft,gright)
STEP 1: increase-release (link4,link5,joint4,gleft,gright,angle180,angle270)
STEP 2: link-to-central-grasp (link2,link3,joint2,joint2,gleft,gright)
STEP 3: decrease-release (link3,link2,joint2,gleft,gright,angle180,angle90)
STEP 4: link-to-central-grasp (link1,link2,joint3,joint1,gleft,gright)
STEP 5: decrease-release (link1,link2,joint1,gleft,gright,angle90,angle0)
