STEP 0: take-links-to-move(link4,link3,joint3,gleft,gright)
STEP 1: increase_angle_first_child(link4,link3,joint3,angle0,angle90,gleft,gright)
STEP 2: release-links(link3,link4,joint3,gleft,gright)
STEP 3: move-link-to-central(link2,joint2,joint1,gright)
STEP 4: take-links-to-move(link2,link1,joint1,gleft,gright)
STEP 5: decrease_angle_first_child(link2,link1,joint1,angle270,angle180,gleft,gright)
STEP 6: decrease_angle_first_child(link2,link1,joint1,angle180,angle90,gleft,gright)
