STEP 0: link-to-central-grasp (link3,link4,joint4,joint3,gleft,gright)
STEP 1: decrease-release (link4,link3,joint3,gleft,gright,angle90,angle0)
STEP 2: link-to-central-grasp (link5,link4,joint4,joint4,gleft,gright)
STEP 3: increase-release (link4,link5,joint4,gleft,gright,angle0,angle270)
STEP 4: link-to-central-grasp (link8,link7,joint2,joint7,gleft,gright)
STEP 5: increase-release (link7,link8,joint7,gleft,gright,angle90,angle180)
STEP 6: link-to-central-grasp (link1,link2,joint5,joint1,gleft,gright)
STEP 7: increase-release (link2,link1,joint1,gleft,gright,angle90,angle180)
