STEP 0: link-to-central-grasp (link3,link4,joint1,joint3,gleft,gright)
STEP 1: increase-release (link4,link3,joint3,gleft,gright,angle90,angle180)
STEP 2: link-to-central-grasp (link7,link8,joint5,joint7,gleft,gright)
STEP 3: decrease-release (link7,link8,joint7,gleft,gright,angle180,angle90)
STEP 4: link-to-central-grasp (link2,link3,joint6,joint2,gleft,gright)
STEP 5: increase-release (link2,link3,joint2,gleft,gright,angle0,angle90)
